import { pgTable, serial, varchar, text, timestamp, integer, pgEnum, index } from 'drizzle-orm/pg-core';
export const roleEnum = pgEnum('role', ['TENANT','OWNER','TECHNICIAN','ADMIN']);
export const priorityEnum = pgEnum('priority', ['LOW','MEDIUM','HIGH','URGENT']);
export const statusEnum = pgEnum('request_status', ['OPEN','ASSIGNED','IN_PROGRESS','RESOLVED','CLOSED']);
const dates = { createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() };
export const users = pgTable('users', { id: serial('id').primaryKey(), name: varchar('name',{length:120}).notNull(), username: varchar('username',{length:80}).notNull().unique(), email: varchar('email',{length:255}).notNull().unique(), passwordHash: text('password_hash').notNull(), role: roleEnum('role').notNull(), ...dates });
export const properties = pgTable('properties', { id: serial('id').primaryKey(), name: varchar('name',{length:150}).notNull(), address: varchar('address',{length:255}).notNull(), city: varchar('city',{length:100}).notNull(), state: varchar('state',{length:100}).notNull(), postalCode: varchar('postal_code',{length:20}).notNull(), ownerId: integer('owner_id').notNull().references(()=>users.id), ...dates }, t=>[index('properties_owner_idx').on(t.ownerId)]);
export const units = pgTable('units', { id: serial('id').primaryKey(), unitNumber: varchar('unit_number',{length:30}).notNull(), propertyId: integer('property_id').notNull().references(()=>properties.id,{onDelete:'cascade'}), tenantId: integer('tenant_id').references(()=>users.id), ...dates }, t=>[index('units_property_idx').on(t.propertyId),index('units_tenant_idx').on(t.tenantId)]);
export const maintenanceRequests = pgTable('maintenance_requests', { id: serial('id').primaryKey(), title: varchar('title',{length:180}).notNull(), description: text('description').notNull(), priority: priorityEnum('priority').notNull().default('MEDIUM'), status: statusEnum('status').notNull().default('OPEN'), propertyId: integer('property_id').notNull().references(()=>properties.id), unitId: integer('unit_id').notNull().references(()=>units.id), reportedBy: integer('reported_by').notNull().references(()=>users.id), assignedTo: integer('assigned_to').references(()=>users.id), resolutionNotes: text('resolution_notes'), ...dates },t=>[index('requests_property_idx').on(t.propertyId),index('requests_unit_idx').on(t.unitId),index('requests_assigned_idx').on(t.assignedTo)]);
